"""Markdown report rendering for churn-workflow evaluations."""

from __future__ import annotations

from pathlib import Path

from .pipeline import ChurnEvaluation


def render_markdown_report(result: ChurnEvaluation) -> str:
    """Render a :class:`ChurnEvaluation` as a Markdown report string.

    The report covers the workflow configuration, a metrics comparison against
    the numeric baseline, the test-set confusion matrix, ranked feature
    importances, and the columns removed by the variance / correlation filters.
    """
    lines: list[str] = []
    lines.append("# feature-engineering-toolkit churn workflow report")
    lines.append("")
    lines.append("## Configuration")
    lines.append("")
    lines.append(f"- Dataset: synthetic churn ({result.n_samples} rows)")
    lines.append(f"- Model: {result.model_name} (seed={result.seed})")
    lines.append(f"- Test split: {result.test_size}")
    lines.append(f"- Engineered features: {result.n_features_engineered}")
    lines.append(f"- Baseline features: {result.n_features_baseline}")
    lines.append(f"- Target churn rate (train): {result.target_rate:.3f}")
    lines.append("")

    lines.append("## Evaluation")
    lines.append("")
    lines.append("| Metric | Engineered | Baseline |")
    lines.append("| --- | ---: | ---: |")
    rows = [
        ("Accuracy", result.accuracy, result.baseline_accuracy),
        ("ROC AUC", result.roc_auc, result.baseline_roc_auc),
        ("Precision", result.precision, None),
        ("Recall", result.recall, None),
        ("F1", result.f1, None),
    ]
    for name, engineered, baseline in rows:
        baseline_str = f"{baseline:.4f}" if baseline is not None else "-"
        lines.append(f"| {name} | {engineered:.4f} | {baseline_str} |")
    lines.append("")

    lines.append("## Confusion matrix (test)")
    lines.append("")
    cm = result.confusion_matrix
    lines.append("| | Pred 0 | Pred 1 |")
    lines.append("| --- | ---: | ---: |")
    lines.append(f"| Actual 0 | {cm[0][0]} | {cm[0][1]} |")
    lines.append(f"| Actual 1 | {cm[1][0]} | {cm[1][1]} |")
    lines.append("")

    lines.append("## Top feature importances")
    lines.append("")
    if result.feature_importances:
        lines.append("| Feature | Importance |")
        lines.append("| --- | ---: |")
        for name, importance in result.feature_importances:
            lines.append(f"| {name} | {importance:.4f} |")
    else:
        lines.append("_no feature importances available_")
    lines.append("")

    lines.append("## Filtering notes")
    lines.append("")
    lines.append(
        "- Dropped by variance threshold: "
        + (", ".join(result.dropped_by_variance) if result.dropped_by_variance else "none")
    )
    lines.append(
        "- Dropped by correlation filter: "
        + (", ".join(result.dropped_by_correlation) if result.dropped_by_correlation else "none")
    )
    lines.append("")

    lines.append("_Report generated by `feature-engineering-toolkit run`._")
    lines.append("")
    return "\n".join(lines)


def save_report(report: str, path: str | Path) -> Path:
    """Write ``report`` to ``path`` (creating parent directories)."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(report, encoding="utf-8")
    return target


__all__ = ["render_markdown_report", "save_report"]
